# python-ssh

FROM python:latest
LABEL Author="lemon"
LABEL mail="<gjlove666@hotmail.com>"

# 时区设置
ENV TZ=Asia/Shanghai
USER root

RUN pip3 install ptvsd

# 暴露端口
EXPOSE 6543

# 用户进入目录
WORKDIR /root
RUN echo "import ptvsd " > server.py
RUN echo "ptvsd.enable_attach()" >> server.py
RUN echo "ptvsd.wait_for_attach()" >> server.py
ENTRYPOINT ["python","-m","ptvsd","--host 0.0.0.0","--port","6543","server.py"]

# build指令
# docker build -t adminhub/ptvsd:latest -f dockerfile  ./

# 创建指令
# docker create -it --name some-ptvsd -p 6543:6543 -v ~/docker-workdir/:/work:rw adminhub/ptvsd:latest
